export const CHANGE_C100 = 'CHANGE_C100';
export const CHANGE_GRAMS = 'CHANGE_GRAMS';
export const CHANGE_MYCALS = 'CHANGE_MYCALS';
export const CHANGE_NOTE = 'CHANGE_NOTE';
export const ADD_TODAY_ENTRY = 'ADD_TODAY_ENTRY';